services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: hackaton-backend-dev
    restart: unless-stopped
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    environment:
      NODE_ENV: development
      DATABASE_PATH: ${DATABASE_PATH:-/usr/src/app/database.sqlite}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - database_data_dev:/usr/src/app
    command: npm run start:dev
    networks:
      - hackaton-backend-network-dev

volumes:
  database_data_dev:

networks:
  hackaton-backend-network-dev:
    driver: bridge

